# Generated by Django 5.0.14 on 2025-06-03 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="数据源名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Excel", "Excel"),
                            ("SQLServer", "SQL Server"),
                            ("XML", "XML"),
                            ("JSON", "JSON"),
                            ("CSV", "CSV"),
                        ],
                        max_length=20,
                        verbose_name="数据源类型",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="文件路径/连接信息",
                    ),
                ),
                (
                    "sheet",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作表"
                    ),
                ),
                (
                    "server",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="服务器地址"
                    ),
                ),
                (
                    "port",
                    models.CharField(
                        blank=True,
                        default="1433",
                        max_length=10,
                        null=True,
                        verbose_name="端口",
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="数据库名称"
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sqlserver", "SQL Server Authentication"),
                            ("windows", "Windows Authentication"),
                        ],
                        default="sqlserver",
                        max_length=20,
                        null=True,
                        verbose_name="身份验证类型",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="密码"
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        blank=True, default=30, null=True, verbose_name="连接超时(秒)"
                    ),
                ),
                (
                    "encrypt",
                    models.BooleanField(default=False, verbose_name="加密连接"),
                ),
                (
                    "trust_server_certificate",
                    models.BooleanField(default=True, verbose_name="信任服务器证书"),
                ),
                (
                    "table",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="表名"
                    ),
                ),
                (
                    "root_path",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="根节点路径"
                    ),
                ),
                (
                    "data_path",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="数据路径"
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        blank=True,
                        default=",",
                        max_length=10,
                        null=True,
                        verbose_name="分隔符",
                    ),
                ),
                (
                    "has_header",
                    models.BooleanField(default=True, verbose_name="包含表头"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "数据资源",
                "verbose_name_plural": "数据资源",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="环境资源名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Python", "Python (requirements.txt)"),
                            ("Java", "Java (pom.xml)"),
                        ],
                        max_length=20,
                        verbose_name="环境资源类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("file_name", models.CharField(max_length=100, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="文件路径"
                    ),
                ),
                (
                    "file_content",
                    models.TextField(blank=True, null=True, verbose_name="文件内容"),
                ),
                (
                    "python_version",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Python版本"
                    ),
                ),
                (
                    "virtual_env_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="虚拟环境名称",
                    ),
                ),
                (
                    "java_version",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Java版本"
                    ),
                ),
                (
                    "maven_version",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Maven版本"
                    ),
                ),
                (
                    "group_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Group ID"
                    ),
                ),
                (
                    "artifact_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Artifact ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        max_length=50,
                        null=True,
                        verbose_name="项目版本",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "环境资源配置",
                "verbose_name_plural": "环境资源配置",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedTestCaseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("generation_method", models.CharField(max_length=50)),
                ("class_name", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=200)),
                ("file_path", models.TextField()),
                ("coverage", models.FloatField(blank=True, null=True)),
                ("effectiveness", models.FloatField(blank=True, null=True)),
                ("diversity", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourceCodeProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="项目名称"),
                ),
                (
                    "project_path",
                    models.CharField(max_length=255, verbose_name="项目路径"),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="项目描述"),
                ),
                (
                    "status",
                    models.CharField(
                        default="unanalyzed", max_length=20, verbose_name="分析状态"
                    ),
                ),
                (
                    "execution_result",
                    models.JSONField(blank=True, null=True, verbose_name="运行结果"),
                ),
            ],
            options={
                "verbose_name": "源代码项目",
                "verbose_name_plural": "源代码项目",
            },
        ),
        migrations.CreateModel(
            name="SourceCodeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(max_length=255, verbose_name="文件路径"),
                ),
                ("language", models.CharField(max_length=50, verbose_name="编程语言")),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="文件描述"),
                ),
                (
                    "status",
                    models.CharField(
                        default="unanalyzed", max_length=20, verbose_name="分析状态"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="web.sourcecodeproject",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "源代码文件",
                "verbose_name_plural": "源代码文件",
            },
        ),
    ]
